INSERT INTO S_REGION (ID,NAME) VALUES (13,'REG13');

UPDATE S_REGION SET NAME = 'GUERRERO' WHERE ID = 13;

DELETE FROM S_REGION WHERE ID = 13;

SELECT * FROM S_REGION;

SELECT * FROM S_REGION WHERE ID = 1;